
# Latest LTS version
FROM clickhouse/clickhouse-server:latest

# Custom Configs
# COPY config.xml /etc/clickhouse-server/config.xml
# COPY users.xml /etc/clickhouse-server/users.xml

# Default ports: 
# 8123 (HTTP)
# 9000 (TCP)
EXPOSE 8123 9000
