
# Latest LTS version
FROM victoriametrics/victoria-metrics:latest

# Persistence and configs
# -retentionPeriod=1m (Metrics older than 1 month deleted) is typically set via args in docker-compose
# COPY prometheus.yml /etc/prometheus/prometheus.yml

# 8428 is the default
EXPOSE 8428
