
FROM quay.io/keycloak/keycloak:latest

# Use PostgreSQL as storage
# Install extra providers if needed
# RUN /opt/keycloak/bin/kc.sh build --db=postgres --db-url= ...

EXPOSE 8080
# Startup script
# ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
