
FROM docker.redpanda.com/redpandadata/redpanda:latest

# Use this to enable developer mode (single node), for production use clustered setup
# ENTRYPOINT ["redpanda", "start", "--mode=dev-container"]
EXPOSE 18081 18082 19092 19644
